-- Phase 5: Property Management & Rent Expiry System Database Schema
-- Business Management System

-- 1. Property Types Table
CREATE TABLE bms_property_types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type_name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  display_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert default property types
INSERT INTO bms_property_types (type_name, description, display_order) VALUES
('Apartment', 'Residential apartment units', 1),
('House', 'Single-family houses', 2),
('Duplex', 'Two-unit residential properties', 3),
('Commercial Space', 'Office or retail spaces', 4),
('Warehouse', 'Storage and warehouse facilities', 5),
('Land', 'Vacant land plots', 6),
('Shop', 'Retail shop spaces', 7),
('Office', 'Office spaces', 8);

-- 2. Properties Table
CREATE TABLE bms_properties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_code VARCHAR(20) UNIQUE NOT NULL,
  property_name VARCHAR(200) NOT NULL,
  property_type_id INT NOT NULL,
  description LONGTEXT,
  address TEXT NOT NULL,
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Nigeria',
  postal_code VARCHAR(20),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  bedrooms INT,
  bathrooms INT,
  size_sqm DECIMAL(10,2),
  floor_number INT,
  parking_spaces INT,
  furnished ENUM('Furnished', 'Semi-Furnished', 'Unfurnished') DEFAULT 'Unfurnished',
  pet_friendly TINYINT(1) DEFAULT 0,
  featured_image VARCHAR(255),
  gallery_images TEXT,
  floor_plan_image VARCHAR(255),
  monthly_rent DECIMAL(15,2) NOT NULL,
  security_deposit DECIMAL(15,2),
  agency_fee DECIMAL(15,2),
  service_charge DECIMAL(15,2),
  currency VARCHAR(10) DEFAULT 'NGN',
  availability_status ENUM('Available', 'Occupied', 'Under Maintenance', 'Reserved') DEFAULT 'Available',
  property_status ENUM('Active', 'Inactive') DEFAULT 'Active',
  year_built INT,
  last_renovated INT,
  owner_name VARCHAR(150),
  owner_contact VARCHAR(100),
  notes TEXT,
  is_featured TINYINT(1) DEFAULT 0,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_type (property_type_id),
  INDEX idx_status (availability_status),
  INDEX idx_rent (monthly_rent),
  INDEX idx_location (city, state),
  FOREIGN KEY (property_type_id) REFERENCES bms_property_types(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Property Features Table
CREATE TABLE bms_property_features (
  id INT AUTO_INCREMENT PRIMARY KEY,
  feature_name VARCHAR(100) UNIQUE NOT NULL,
  feature_category ENUM('Amenities', 'Security', 'Utilities', 'Other') DEFAULT 'Amenities',
  icon VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert common features
INSERT INTO bms_property_features (feature_name, feature_category) VALUES
('Air Conditioning', 'Amenities'),
('Heating', 'Amenities'),
('Swimming Pool', 'Amenities'),
('Gym', 'Amenities'),
('Elevator', 'Amenities'),
('Balcony', 'Amenities'),
('Garden', 'Amenities'),
('Generator', 'Utilities'),
('Water Supply', 'Utilities'),
('Internet/WiFi', 'Utilities'),
('Cable TV', 'Utilities'),
('Security Guard', 'Security'),
('CCTV', 'Security'),
('Gated Community', 'Security'),
('Fire Safety', 'Security'),
('Laundry Room', 'Amenities'),
('Storage Space', 'Amenities'),
('Playground', 'Amenities');

-- 4. Property-Feature Mapping Table
CREATE TABLE bms_property_feature_map (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_id INT NOT NULL,
  feature_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_property_feature (property_id, feature_id),
  FOREIGN KEY (property_id) REFERENCES bms_properties(id) ON DELETE CASCADE,
  FOREIGN KEY (feature_id) REFERENCES bms_property_features(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Tenants Table
CREATE TABLE bms_tenants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_code VARCHAR(20) UNIQUE NOT NULL,
  title ENUM('Mr', 'Mrs', 'Miss', 'Dr', 'Prof', 'Chief') DEFAULT 'Mr',
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  date_of_birth DATE,
  gender ENUM('Male', 'Female', 'Other'),
  marital_status ENUM('Single', 'Married', 'Divorced', 'Widowed'),
  occupation VARCHAR(150),
  employer_name VARCHAR(150),
  employer_address TEXT,
  email VARCHAR(150),
  phone VARCHAR(20) NOT NULL,
  alt_phone VARCHAR(20),
  current_address TEXT,
  permanent_address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Nigeria',
  id_type ENUM('National ID', 'Drivers License', 'Passport', 'Voters Card', 'Other'),
  id_number VARCHAR(50),
  id_document VARCHAR(255),
  passport_photo VARCHAR(255),
  emergency_contact_name VARCHAR(150),
  emergency_contact_phone VARCHAR(20),
  emergency_contact_relationship VARCHAR(50),
  employment_letter VARCHAR(255),
  bank_statement VARCHAR(255),
  reference_name VARCHAR(150),
  reference_phone VARCHAR(20),
  reference_address TEXT,
  notes TEXT,
  status ENUM('Active', 'Inactive', 'Blacklisted') DEFAULT 'Active',
  customer_id INT,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_phone (phone),
  INDEX idx_email (email),
  INDEX idx_name (first_name, last_name),
  FOREIGN KEY (customer_id) REFERENCES bms_customers(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Leases Table
CREATE TABLE bms_leases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lease_number VARCHAR(50) UNIQUE NOT NULL,
  property_id INT NOT NULL,
  tenant_id INT NOT NULL,
  lease_type ENUM('New', 'Renewal') DEFAULT 'New',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  lease_term_months INT NOT NULL,
  monthly_rent DECIMAL(15,2) NOT NULL,
  security_deposit DECIMAL(15,2),
  agency_fee DECIMAL(15,2),
  legal_fee DECIMAL(15,2),
  service_charge DECIMAL(15,2),
  total_upfront_payment DECIMAL(15,2),
  rent_payment_day INT DEFAULT 1,
  rent_payment_frequency ENUM('Monthly', 'Quarterly', 'Bi-Annually', 'Annually') DEFAULT 'Monthly',
  grace_period_days INT DEFAULT 0,
  late_fee_percentage DECIMAL(5,2) DEFAULT 0,
  payment_method ENUM('Cash', 'Bank Transfer', 'Check', 'Direct Debit') DEFAULT 'Bank Transfer',
  auto_renewal TINYINT(1) DEFAULT 0,
  renewal_notice_days INT DEFAULT 60,
  lease_agreement_file VARCHAR(255),
  terms_conditions TEXT,
  special_clauses TEXT,
  signed_by_tenant TINYINT(1) DEFAULT 0,
  signed_by_landlord TINYINT(1) DEFAULT 0,
  witness_name VARCHAR(150),
  witness_signature VARCHAR(255),
  lease_status ENUM('Draft', 'Active', 'Expired', 'Terminated', 'Renewed') DEFAULT 'Draft',
  activation_date DATE,
  termination_date DATE,
  termination_reason TEXT,
  expiry_reminder_sent TINYINT(1) DEFAULT 0,
  last_reminder_date DATE,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_property (property_id),
  INDEX idx_tenant (tenant_id),
  INDEX idx_status (lease_status),
  INDEX idx_dates (start_date, end_date),
  INDEX idx_expiry_check (end_date, lease_status, expiry_reminder_sent),
  FOREIGN KEY (property_id) REFERENCES bms_properties(id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id) REFERENCES bms_tenants(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Rent Payments Table
CREATE TABLE bms_rent_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payment_number VARCHAR(50) UNIQUE NOT NULL,
  lease_id INT NOT NULL,
  property_id INT NOT NULL,
  tenant_id INT NOT NULL,
  payment_date DATE NOT NULL,
  payment_type ENUM('Security Deposit', 'Agency Fee', 'Legal Fee', 'Service Charge', 'Monthly Rent', 'Arrears', 'Late Fee', 'Other') NOT NULL,
  period_from DATE,
  period_to DATE,
  amount DECIMAL(15,2) NOT NULL,
  late_fee DECIMAL(15,2) DEFAULT 0,
  total_amount DECIMAL(15,2) NOT NULL,
  payment_method ENUM('Cash', 'Bank Transfer', 'Check', 'Credit Card', 'Mobile Money', 'Other') NOT NULL,
  reference_number VARCHAR(100),
  bank_account_id INT,
  receipt_number VARCHAR(50),
  notes TEXT,
  payment_status ENUM('Pending', 'Completed', 'Failed', 'Refunded') DEFAULT 'Completed',
  invoice_id INT,
  payment_id INT,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_lease (lease_id),
  INDEX idx_property (property_id),
  INDEX idx_tenant (tenant_id),
  INDEX idx_payment_date (payment_date),
  INDEX idx_period (period_from, period_to),
  INDEX idx_status (payment_status),
  FOREIGN KEY (lease_id) REFERENCES bms_leases(id) ON DELETE RESTRICT,
  FOREIGN KEY (property_id) REFERENCES bms_properties(id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id) REFERENCES bms_tenants(id) ON DELETE RESTRICT,
  FOREIGN KEY (bank_account_id) REFERENCES bms_accounts(id) ON DELETE SET NULL,
  FOREIGN KEY (invoice_id) REFERENCES bms_invoices(id) ON DELETE SET NULL,
  FOREIGN KEY (payment_id) REFERENCES bms_payments(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Rent Reminders Table
CREATE TABLE bms_rent_reminders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lease_id INT NOT NULL,
  tenant_id INT NOT NULL,
  reminder_type ENUM('Expiry Alert', 'Rent Due', 'Overdue Notice', 'Renewal Notice') NOT NULL,
  reminder_date DATE NOT NULL,
  days_before INT,
  message TEXT,
  sent_via ENUM('Email', 'SMS', 'Both') DEFAULT 'Email',
  sent_at TIMESTAMP NULL,
  status ENUM('Pending', 'Sent', 'Failed') DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_lease (lease_id),
  INDEX idx_date (reminder_date),
  INDEX idx_status (status),
  FOREIGN KEY (lease_id) REFERENCES bms_leases(id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id) REFERENCES bms_tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. Maintenance Requests Table
CREATE TABLE bms_maintenance_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_number VARCHAR(50) UNIQUE NOT NULL,
  property_id INT NOT NULL,
  lease_id INT,
  tenant_id INT,
  request_type ENUM('Plumbing', 'Electrical', 'HVAC', 'Appliance', 'Structural', 'Pest Control', 'Cleaning', 'Other') NOT NULL,
  priority ENUM('Low', 'Medium', 'High', 'Emergency') DEFAULT 'Medium',
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  location_in_property VARCHAR(255),
  reported_date DATE NOT NULL,
  preferred_date DATE,
  preferred_time VARCHAR(50),
  images TEXT,
  assigned_to INT,
  assigned_date DATE,
  status ENUM('Pending', 'In Progress', 'Completed', 'Cancelled', 'On Hold') DEFAULT 'Pending',
  started_date DATE,
  completed_date DATE,
  estimated_cost DECIMAL(15,2),
  actual_cost DECIMAL(15,2),
  expense_id INT,
  vendor_name VARCHAR(150),
  vendor_contact VARCHAR(100),
  work_performed TEXT,
  parts_used TEXT,
  completion_notes TEXT,
  tenant_satisfaction ENUM('Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very Dissatisfied'),
  tenant_feedback TEXT,
  is_emergency TINYINT(1) DEFAULT 0,
  requires_entry TINYINT(1) DEFAULT 1,
  entry_permission_granted TINYINT(1) DEFAULT 0,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_property (property_id),
  INDEX idx_tenant (tenant_id),
  INDEX idx_status (status),
  INDEX idx_priority (priority),
  INDEX idx_assigned (assigned_to),
  INDEX idx_dates (reported_date, completed_date),
  FOREIGN KEY (property_id) REFERENCES bms_properties(id) ON DELETE RESTRICT,
  FOREIGN KEY (lease_id) REFERENCES bms_leases(id) ON DELETE SET NULL,
  FOREIGN KEY (tenant_id) REFERENCES bms_tenants(id) ON DELETE SET NULL,
  FOREIGN KEY (assigned_to) REFERENCES bms_users(id) ON DELETE SET NULL,
  FOREIGN KEY (expense_id) REFERENCES bms_expenses(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. Property Inspections Table
CREATE TABLE bms_property_inspections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  inspection_number VARCHAR(50) UNIQUE NOT NULL,
  property_id INT NOT NULL,
  lease_id INT,
  tenant_id INT,
  inspection_type ENUM('Move-In', 'Move-Out', 'Routine', 'Maintenance', 'Emergency') NOT NULL,
  inspection_date DATE NOT NULL,
  inspection_time TIME,
  inspector_name VARCHAR(150),
  inspector_id INT,
  overall_condition ENUM('Excellent', 'Good', 'Fair', 'Poor', 'Needs Repair') NOT NULL,
  cleanliness ENUM('Excellent', 'Good', 'Fair', 'Poor') NOT NULL,
  walls_condition TEXT,
  floors_condition TEXT,
  ceiling_condition TEXT,
  windows_doors_condition TEXT,
  kitchen_condition TEXT,
  bathroom_condition TEXT,
  electrical_condition TEXT,
  plumbing_condition TEXT,
  appliances_condition TEXT,
  hvac_condition TEXT,
  damages_found TEXT,
  repair_needed TEXT,
  estimated_repair_cost DECIMAL(15,2),
  images TEXT,
  inspection_report_file VARCHAR(255),
  tenant_present TINYINT(1) DEFAULT 0,
  tenant_signature VARCHAR(255),
  landlord_signature VARCHAR(255),
  notes TEXT,
  next_inspection_date DATE,
  status ENUM('Scheduled', 'Completed', 'Cancelled') DEFAULT 'Scheduled',
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_property (property_id),
  INDEX idx_lease (lease_id),
  INDEX idx_type (inspection_type),
  INDEX idx_date (inspection_date),
  INDEX idx_status (status),
  FOREIGN KEY (property_id) REFERENCES bms_properties(id) ON DELETE RESTRICT,
  FOREIGN KEY (lease_id) REFERENCES bms_leases(id) ON DELETE SET NULL,
  FOREIGN KEY (tenant_id) REFERENCES bms_tenants(id) ON DELETE SET NULL,
  FOREIGN KEY (inspector_id) REFERENCES bms_users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. Property Documents Table
CREATE TABLE bms_property_documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_id INT,
  lease_id INT,
  tenant_id INT,
  document_type ENUM('Lease Agreement', 'Title Deed', 'Survey Plan', 'Building Permit', 'Insurance Policy', 'Tenant ID', 'Tenant Photo', 'Bank Statement', 'Employment Letter', 'Utility Bill', 'Inspection Report', 'Maintenance Receipt', 'Other') NOT NULL,
  document_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  file_size INT,
  file_type VARCHAR(50),
  description TEXT,
  upload_date DATE NOT NULL,
  expiry_date DATE,
  uploaded_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_property (property_id),
  INDEX idx_lease (lease_id),
  INDEX idx_tenant (tenant_id),
  INDEX idx_type (document_type),
  FOREIGN KEY (property_id) REFERENCES bms_properties(id) ON DELETE CASCADE,
  FOREIGN KEY (lease_id) REFERENCES bms_leases(id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id) REFERENCES bms_tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (uploaded_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. Lease History Table
CREATE TABLE bms_lease_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lease_id INT NOT NULL,
  action VARCHAR(100) NOT NULL,
  description TEXT,
  old_value TEXT,
  new_value TEXT,
  performed_by INT,
  performed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_lease (lease_id),
  FOREIGN KEY (lease_id) REFERENCES bms_leases(id) ON DELETE CASCADE,
  FOREIGN KEY (performed_by) REFERENCES bms_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
